# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  ebanux@v2:
    root: openapi/openapi.yaml
styleguide:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index-tmpl.html
  theme:
    colors:
      primary:
        main: "#32329f"
    logo:
      maxWidth: 200px
    sidebar:
      groupItems:
        textTransform: uppercase
      level1items:
        textTransform: uppercase
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
