openapi: 3.1.0
info:
  version: 2.0.0
  title: Ebanux-Back - API
  termsOfService: 'https://www.ebanux.com/terms'
  contact:
    email: support@ebanux.com
    url: 'https://ebanux.slack.com/messages/support'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'logo.png'
    altText: Ebanux-Back
  description:
    $ref: ./info-description.md
tags:
  - name: Products
    description: |
      TODO: ...
  - name: Coupons
    description: |
      TODO: ...
  - name: Prices
    description: |
      TODO: ...
  - name: Payment-Links
    description: |
      TODO: ...
  - name: Customers
    description: |
      TODO: ...
  - name: Subscriptions
    description: |
      TODO: ...
  - name: Users
    description: |
      TODO: ...
servers:
  - url: 'https://dev.ebanux.link/api/v2.0'

paths:
  /subscriptions:
    $ref: paths/subscriptions.yaml
  /subscriptions/{id}:
    $ref: paths/subscriptions@{id}.yaml
  /products:
    $ref: paths/products.yaml
  /products/{id}:
    $ref: paths/products@{id}.yaml
  /payment/links:
    $ref: paths/payment@links.yaml
  /payment/links/{id}:
    $ref: paths/payment@links@{id}.yaml
  /customers:
    $ref: paths/customers.yaml
  /customers/{id}:
    $ref: paths/customers@{id}.yaml
  /prices:
    $ref: paths/prices.yaml
  /prices/{id}:
    $ref: paths/prices@{id}.yaml
  /coupons:
    $ref: paths/coupons.yaml
  /coupons/{id}:
    $ref: paths/coupons@{id}.yaml
security:
  - AWS-Cognito: []

components:
  securitySchemes:
    AWS-Cognito:
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://dev.ebanux.link/api/v2.0/oauth/token'
          refreshUrl: 'https://dev.ebanux.link/api/v2.0/oauth/token'
          scopes:
            'manage': Admin all resources
